### PR TITLE
Use ssh with ConnectTimeout=5

### PR DESCRIPTION
**Pull request by derekhiggins**
I've seen the ssh to check if the master API is ready
(in 07_deploy_masters.sh) hang and have to be killed for the
script to move one, presumably this was something to do
with the VIP moving from the bootstrap node to the master.
Add a timeout to all ssh commands to prevent this from happening,
also create a common SSH env variable for all ssh commands.

### CODE REVIEW

**Comment by derekhiggins** [comment]
Build FAILURE, see build http://10.8.144.11:8080/job/dev-tools/101/

**Comment by derekhiggins** [comment]
> Build FAILURE, see build http://10.8.144.11:8080/job/dev-tools/101/

> ++ oc --config ocp/auth/kubeconfig get nodes
> ++ grep 'master-[0-2] *Ready'
> ++ wc -l
> No resources found.
> The connection to the server api.ostest.test.metalkube.org:6443 was refused - did you specify the right host or port?
> + NODES_ACTIVE=0
> make: *** [ocp_run] Error 1

Not sure what happened there and don't have the logs, gonna re-trigger it for now

**Comment by derekhiggins** [comment]
Build SUCCESS, see build http://10.8.144.11:8080/job/dev-tools/103/

**Comment by derekhiggins** [comment]
I've seen this happen again, even with ConnectTimeout=5 , so I've added a hard kill after 5 seconds to the command I've seen it on (twice)

**Comment by hardys** [comment]
Looks good to me, but added a question/comment re why the ssh session is hanging

**Comment by derekhiggins** [comment]
Build SUCCESS, see build http://10.8.144.11:8080/job/dev-tools/104/

**Pull request merged**
